export { default as Navbar } from './Navbars/Navbar'
export { default as ImageSlide } from './Sliders/ImageSlide'
export { default as ShapeHeader } from './ShapeHeader/ShapeHeader'
export { default as GeneralInfo } from './GeneralInfo/GeneralInfo'
export { default as Presentation } from './GeneralInfo/Presentation'
export { default as EmblaCarousel } from './Sliders/EmblaCarousel'