export const skillss = [
    "C#",
    "ASP.NET MVC",
    "ASP.NET Core",
    "Entity Framework",
    "Angular",
    "Node.js",
    "jQuery",
    "HTML5",
    "CSS3",
    "Sass",
    "MS SQL Server",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Git",
    "GitHub",
    "Scrum",
    "Docker",
    "Bootstrap",
    "AngularJS",
    "NestJS",
    "TypeScript",
    "JavaScript",
    "React.js"
];

export const skills = {
    ES:{
        title:'Habilidades y Competencias',
        skills:[
        { title: "C#", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/csharp.svg" },
        { title: "ASP.NET MVC", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dot-net.svg" },
        { title: "ASP.NET Core", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dot-net.svg" },
        { title: "Entity Framework", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dot-net.svg" },
        { title: "Angular", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/angular.svg" },
        { title: "Node.js", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/nodedotjs.svg" },
        { title: "jQuery", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/jquery.svg" },
        { title: "HTML5", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/html5.svg" },
        { title: "CSS3", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/css3.svg" },
        { title: "Sass", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/sass.svg" },
        { title: "MS SQL Server", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/microsoftsqlserver.svg" },
        { title: "MySQL", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/mysql.svg" },
        { title: "PostgreSQL", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/postgresql.svg" },
        { title: "MongoDB", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/mongodb.svg" },
        { title: "Git", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/git.svg" },
        { title: "GitHub", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/github.svg" },
        { title: "Scrum", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/scrumalliance.svg" },
        { title: "Docker", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/docker.svg" },
        { title: "Bootstrap", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/bootstrap.svg" },
        { title: "AngularJS", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/angularjs.svg" },
        { title: "NestJS", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/nestjs.svg" },
        { title: "TypeScript", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/typescript.svg" },
        { title: "JavaScript", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/javascript.svg" },
        { title: "React.js", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/react.svg" },
    ]
},
    EN:{
        title:'Skills and Competencies',
        skills:[
        { title: "C#", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/csharp.svg" },
        { title: "ASP.NET MVC", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dot-net.svg" },
        { title: "ASP.NET Core", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dot-net.svg" },
        { title: "Entity Framework", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dot-net.svg" },
        { title: "Angular", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/angular.svg" },
        { title: "Node.js", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/nodedotjs.svg" },
        { title: "jQuery", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/jquery.svg" },
        { title: "HTML5", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/html5.svg" },
        { title: "CSS3", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/css3.svg" },
        { title: "Sass", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/sass.svg" },
        { title: "MS SQL Server", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/microsoftsqlserver.svg" },
        { title: "MySQL", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/mysql.svg" },
        { title: "PostgreSQL", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/postgresql.svg" },
        { title: "MongoDB", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/mongodb.svg" },
        { title: "Git", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/git.svg" },
        { title: "GitHub", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/github.svg" },
        { title: "Scrum", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/scrumalliance.svg" },
        { title: "Docker", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/docker.svg" },
        { title: "Bootstrap", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/bootstrap.svg" },
        { title: "AngularJS", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/angularjs.svg" },
        { title: "NestJS", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/nestjs.svg" },
        { title: "TypeScript", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/typescript.svg" },
        { title: "JavaScript", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/javascript.svg" },
        { title: "React.js", image: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/react.svg" },
    ]
}
};
